### ISSUE TITLE
bmatrix support

### ISSUE THREAD

**Issue by rowanc1** [continuous-foundation/tex-to-typst#6]
$$ \begin{bmatrix} 
	sr_1 & sr_2 & t_x\\
	sr_3 & sr_4 & t_y\\
	0 & 0 & 1
\end{bmatrix} \begin{bmatrix} 
    x_t\\
	y_t\\
	1
\end{bmatrix} = \begin{bmatrix} 
    x_s\\
	y_s\\
	1
\end{bmatrix}
$$ 

$$ \begin{bmatrix} 
	1 & 0 & t_x\\
	0 & 1 & 0\\
	0 & 0 & 1
\end{bmatrix}
$$

cc @thesamovar

**Comment by thesamovar** [comment]
Thanks!
